import Head from 'next/head';
import Layout from '../Layout';
import '../styles/globals.css';
import { React } from 'react';

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Htet</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
