import Head from 'next/head';

import HomePage from '../views/HomePage';
import WebApp from '../layout/WebApp';

export default function Home(prpos) {
  return (
    <>
      <Head>
        <title>Htet</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <HomePage />
    </>
  );
}
