import Head from "next/head";

import HomePage from "../views/HomePage";
import Footer from "../layout/Footer";
import Header from "../layout/Header";
import WebApp from "../layout/WebApp";

export default function Home(prpos) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit&display=swap"
          rel="stylesheet"
        />
      </Head>

      <WebApp>
        <HomePage />
      </WebApp>
    </>
  );
}
